AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  DatabaseUrl:
    Type: String
    Description: PostgreSQL database connection URL for Aurora RDS
    NoEcho: true
    Default: ""

Globals:
  Function:
    Timeout: 30
    MemorySize: 1024
    Runtime: nodejs20.x
    Architectures: ["arm64"]
    Environment:
      Variables:
        NODE_OPTIONS: "--enable-source-maps"
    EphemeralStorage:
      Size: 512
  Api:
    OpenApiVersion: "2.0"
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'Content-Type,Authorization'"
      AllowOrigin: "'*'"
      MaxAge: 600

Resources:
  NodeModulesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: yjp-nestjs-dependencies
      Description: Node modules for NestJS application
      ContentUri: layer/
      CompatibleRuntimes:
        - nodejs20.x
      RetentionPolicy: Retain

  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      BinaryMediaTypes:
        - "image/*"
        - "multipart/form-data"
      Auth:
        DefaultAuthorizer: NONE

  NestJSFunction:
    Type: AWS::Serverless::Function
    Metadata:
      SkipBuild: true
    Properties:
      Handler: src/lambda.handler
      CodeUri: ./dist
      MemorySize: 3008
      Timeout: 30
      Layers:
        - !Ref NodeModulesLayer
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
          NODE_ENV: production
          NODE_PATH: /var/task/node_modules:/opt/nodejs/node_modules
          URL_PREFIX: /dev
      Policies:
        - VPCAccessPolicy: {}
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref Api
        RootEvent:
          Type: Api
          Properties:
            Path: /
            Method: ANY
            RestApiId: !Ref Api
            Auth:
              Authorizer: NONE
      AutoPublishAlias: live

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/dev"
  FunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt NestJSFunction.Arn
