AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  DatabaseUrl:
    Type: String
    Description: PostgreSQL database connection URL for Aurora RDS
    NoEcho: true
    Default: ""

  # VPC配置参数 - 1个公有子网 + 3个私有子网
  SecurityGroupId:
    Type: String
    Default: "sg-0f80dcde1e5a3dbbc"
    Description: VPC安全组ID (ec2-rds-1 - 用于连接RDS)

  PublicSubnetId:
    Type: String
    Default: "subnet-0e5c8131a811adc95"
    Description: 公有子网 ID (us-west-2a, 172.31.32.0/20) - 用于访问外网

  PrivateSubnet1Id:
    Type: String
    Default: "subnet-0782da7395e112a97"
    Description: 私有子网1 ID (us-west-2a, 172.31.64.0/20) - Lambda部署

  PrivateSubnet2Id:
    Type: String
    Default: "subnet-03da04142d46ba4f6"
    Description: 私有子网2 ID (us-west-2b, 172.31.80.0/20) - Lambda部署

  PrivateSubnet3Id:
    Type: String
    Default: "subnet-081e618ba9e6219bd"
    Description: 私有子网3 ID (us-west-2c, 172.31.96.0/20) - Lambda部署

  EnableVPC:
    Type: String
    Default: "true"
    AllowedValues: ["true", "false"]
    Description: 是否启用VPC配置

Conditions:
  UseVPC: !Equals [!Ref EnableVPC, "true"]

Globals:
  Function:
    Timeout: 30
    MemorySize: 1024
    Runtime: nodejs20.x
    Architectures: ["arm64"]
    Environment:
      Variables:
        NODE_OPTIONS: "--enable-source-maps"
    EphemeralStorage:
      Size: 512
  Api:
    OpenApiVersion: "2.0"
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'Content-Type,Authorization'"
      AllowOrigin: "'*'"
      MaxAge: 600

Resources:
  NodeModulesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: yjp-nestjs-dependencies
      Description: Node modules for NestJS application
      ContentUri: layer/
      CompatibleRuntimes:
        - nodejs20.x
      RetentionPolicy: Retain

  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      BinaryMediaTypes:
        - "image/*"
        - "multipart/form-data"
      Auth:
        DefaultAuthorizer: NONE

  NestJSFunction:
    Type: AWS::Serverless::Function
    Metadata:
      SkipBuild: true
    Properties:
      Handler: src/lambda.handler
      CodeUri: ./dist
      MemorySize: 3008
      Timeout: 30
      Layers:
        - !Ref NodeModulesLayer
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
          NODE_ENV: production
          NODE_PATH: /var/task/node_modules:/opt/nodejs/node_modules
          URL_PREFIX: /dev
          VPC_SUBNETS: "private-subnets-cleanup-v3"
      # VPC配置 - 使用现有VPC的子网和安全组
      VpcConfig: !If
        - UseVPC
        - SecurityGroupIds:
            - !Ref SecurityGroupId
          SubnetIds:
            - !Ref PrivateSubnet1Id
            - !Ref PrivateSubnet2Id
            - !Ref PrivateSubnet3Id
        - !Ref AWS::NoValue
      Policies:
        - VPCAccessPolicy: {}
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref Api
            Auth:
              Authorizer: NONE
        RootEvent:
          Type: Api
          Properties:
            Path: /
            Method: ANY
            RestApiId: !Ref Api
            Auth:
              Authorizer: NONE
      AutoPublishAlias: live

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/dev"

  FunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt NestJSFunction.Arn

  # VPC配置信息
  VPCEnabled:
    Description: VPC是否启用
    Value: !Ref EnableVPC

  UsedSecurityGroup:
    Condition: UseVPC
    Description: 使用的安全组ID
    Value: !Ref SecurityGroupId

  UsedSubnets:
    Condition: UseVPC
    Description: 使用的子网IDs
    Value: !Sub "${PrivateSubnet1Id}, ${PrivateSubnet2Id}, ${PrivateSubnet3Id}"
